### ISSUE TITLE
[engawa]ステータスページの説明文がない

### ISSUE THREAD

**Issue by penginn-0** [1673beta/cherrypick#17]
### 💡 Summary

![image](https://github.com/1673beta/cherrypick/assets/121443048/3782b94b-f29f-43e1-9d65-8afa4c292289)
![image](https://github.com/1673beta/cherrypick/assets/121443048/0ff291ba-5fe1-4be1-9b2f-bbb5e1568d6b)

### 🥰 Expected Behavior

説明文がある

### 🤬 Actual Behavior

説明文がない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* CherryPick:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:https://github.com/1673beta/cherrypick/commit/d6d8e4899d97976a75c9889d64016988dce478e3
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by 1673beta** [comment]
fixed
