### ISSUE TITLE
メディアタイムラインでリノートが表示されない

### ISSUE THREAD

**Issue by penginn-net** [1673beta/cherrypick#24]
### 💡 Summary

メディアタイムラインで参照している?GTLの画像を含むリノートが表示されていない

### 🥰 Expected Behavior

画像を含むリノートが表示される

### 🤬 Actual Behavior

画像を含むリノートが表示されていない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* CherryPick:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:4.7.0-beta.3-engawa0.3.0
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by 1673beta** [comment]
仕様だったと思うけど、表示するように仕様変更する予定

**Comment by 1673beta** [comment]
仕様変更の予定は無くなりました
