### ISSUE TITLE
リポジトリURL変える

### ISSUE THREAD

**Issue by 1673beta** [1673beta/cherrypick#3]
### Summary

リンクするリポジトリURLを変更or「CherryPickについて」のページを変更

### Purpose

AGPLに引っかかりそうなので

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by 1673beta** [comment]
本体の機能に変えるやつがあったのでいらないことに気が付いた

**Comment by penginn-0** [comment]
デフォで変えてあると嬉しいかも
