### ISSUE TITLE
デッキモードで追加したタイムラインカラムが正しく動作せず、また削除もできない

### ISSUE THREAD

**Issue by penginn-0** [1673beta/cherrypick#32]
### 💡 Summary

デッキモードで追加したタイムラインカラムが正しく動作せず、また削除もできない

### 🥰 Expected Behavior

デッキモードで追加したタイムラインカラムが正しく動作する
削除もできる

### 🤬 Actual Behavior

デッキモードで追加したタイムラインカラムが正しく動作しない
削除もできない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* CherryPick:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by 1673beta** [comment]
治ってるのでclose(多分どこかで直した)
