### ISSUE TITLE
TLのリモートリアクション表示が吹っ飛んでる

### ISSUE THREAD

**Issue by penginn-0** [1673beta/cherrypick#38]
### 💡 Summary

![Screenshot_20240325_144628_Chrome](https://github.com/1673beta/cherrypick/assets/121443048/cd4ca8f3-e20a-419f-b5cb-792d365c5c16)

### 🥰 Expected Behavior

ある

### 🤬 Actual Behavior

ない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* CherryPick:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by penginn-0** [comment]
ccdaded95cf5024db358baa8b99f6a0bfe2eb97b

**Comment by penginn-0** [comment]
いろいろしてたら復活しました🙏

**Comment by penginn-0** [comment]
リモート絵文字表示が壊れてる感じ
デフォとローカルは表示される

**Comment by 1673beta** [comment]
なおしたのでclose
