### ISSUE TITLE
高度な検索

### ISSUE THREAD

**Issue by penginn-0** [1673beta/cherrypick#40]
### Summary

ファイル含むかに加えてあったら良さそうなのを
- 日時指定(時間→misskeyid)After/Before
- NSFW(ファイル検索と同じ感じ)
- ホスト指定
- ホスト除外
- ユーザ除外(ユーザ指定の逆)
- リプライ除外
- OR 
- AND 
- NOT

### Purpose

便利

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by 1673beta** [comment]
yojo-artフォークである程度実装したのでclose
